Repository MicrosoftDocs/appcenter-docs, pull requests merged in 2020-11, with the labels that each got.

#1162 Command Update: CodePush Android Note Instructions
  docs/distribution/codepush/rn-deployment.md
Labels: Change sent to author, app-center-distribute/subsvc, ready-to-merge, vs-appcenter/svc

#1168 Update vsts-deploy.md
  docs/distribution/vsts-deploy.md
Labels: Change sent to author, app-center-distribute/subsvc, do-not-merge, vs-appcenter/svc

#1175 Wrong command on android setup section.
  docs/distribution/codepush/rn-get-started.md
Labels: Change sent to author, app-center-distribute/subsvc, vs-appcenter/svc
